apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: main-app
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: argocd-apps
    repoURL: 'https://github.com/sridharakb05/argo-app-of-apps.git'
    targetRevision: HEAD
    directory:
      recurse: true
  project: nginx
