apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: nginx-helm
    repoURL: 'https://github.com/sridharakb05/argo-app-of-apps.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  project: nginx